<a href="https://colab.research.google.com/github/rrachxz/learning-phyton/blob/library%2Fnumpy/tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import pandas as pd

In [16]:
# task 1
array = np.array([[0, 3], [2, 5]])
print(array.shape)

(2, 2)


In [17]:
# task 2
np.random.seed(0)
x = np.random.randint(8, size=(3, 4))
print(x)

[[4 7 5 0]
 [3 3 3 7]
 [1 3 5 2]]


In [30]:
# task 3
x = np.ones((3, 3))
y = np.zeros((3, 3))
print(x, y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
# task 4
np.random.seed(0)
x = np.random.randint(10, size=(6, 3))
print(x.T)

[[8 9 4 3 2 1]
 [1 8 3 5 3 3]
 [5 9 0 0 8 3]]


In [13]:
# task 5
np.random.seed(0)
n = np.random.randint(1, 10)
p = np.random.randint(1, 10)
m = np.random.randint(1, 10)
x = np.random.randint(10, size=(n, p))
y = np.random.randint(10, size=(p, m))
print(x.dot(y))

# i have finished the tasks

[[12 21 18 24]
 [28 49 42 56]
 [36 63 54 72]
 [12 21 18 24]
 [20 35 30 40]
 [ 8 14 12 16]]
